version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "devel"
    reviewers:
      - "adriancleung"
      
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
    target-branch: "devel"
    reviewers:
      - "adriancleung"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "devel"
    reviewers:
      - "adriancleung"
