name: Lint

on:
  pull_request:
    branches: [ master, devel ]
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persistent-credentials: false
      
      - name: Reconfigure git to use HTTP authentication
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint